name: layer_first_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
  meta: ^1.8.0
  mocktail: ^0.3.0