name: todo_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  layer_first_api:
    path: ../layer_first_api

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mocktail: ^0.3.0